CREATE TABLE project (Id INTEGER PRIMARY KEY,
title TEXT,
category TEXT,
funding goal INTEGER,
start date INTEGER,
end date INTEGER);

CREATE TABLE users (id INTEGER PRIMARY KEY);
CREATE TABLE pledges (id INTEGER PRIMARY KEY);
